Task:
The Nautilus DevOps team is planning to deploy some micro services on Kubernetes platform. 
The team has already set up a Kubernetes cluster and now they want set up some namespaces,
deployments etc. Based on the current requirements, the team has shared some details as below:


Create a namespace named dev and create a POD under it; 
name the pod dev-nginx-pod and use nginx image with latest tag only and remember to mention tag i.e nginx:latest.


kubectl run dev-nginx-pod --image=nginx:latest --namespace=dev -o yaml --dry-run=client > nspod.yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dev-nginx-pod
  name: dev-nginx-pod
  namespace: dev
spec:
  containers:
  - image: nginx:latest
    name: dev-nginx-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}