# Task2:

1.Create a pod named webserver.

2.Create an emptyDir volume shared-logs.

3.Create two containers from nginx and ubuntu images with latest tag only and remember to mention tag i.e nginx:latest, nginx container name should be nginx-container and ubuntu container name should be sidecar-container on webserver pod.

4.Add command on sidecar-container "sh","-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"

5.Mount the volume shared-logs on both containers at location /var/log/nginx, all containers should be up and running.

#yaml

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver
  name: webserver
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  containers:
  - image: nginx:latest
    name: nginx-container
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx

  - image: ubuntu:latest
    name: sidecar-container 
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    commad: ["/bin/sh"]
    args: ["-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"]


    